# Generated by Django 5.1.2 on 2024-12-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_matches_game_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='game_datetime',
        ),
        migrations.AddField(
            model_name='matches',
            name='date',
            field=models.DateField(default='2024-1-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matches',
            name='time',
            field=models.TimeField(default='00:00:01'),
            preserve_default=False,
        ),
    ]
