# Generated by Django 5.1.2 on 2024-12-01 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rank', models.SmallIntegerField(blank=True, default=0)),
                ('logo', models.ImageField(blank=True, default='profile_images/default_team.jpg', null=True, upload_to='profile_images')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_founded', models.DateField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('wins', models.SmallIntegerField(default=0)),
                ('draws', models.SmallIntegerField(default=0)),
                ('loses', models.SmallIntegerField(default=0)),
                ('administrators', models.ManyToManyField(related_name='administered_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
