# Generated by Django 5.1.4 on 2024-12-10 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='administered_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
