db:
  restart: always
  image: postgres
  container_name: SvilenPostgres
  volumes:
    - postgres_data:/var/lib/postgresql/data/
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=svilkata12
    - POSTGRES_DB=teams
  ports:
    - "5432:5432"
  networks:
