# Generated by Django 5.1.4 on 2024-12-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_matches_game_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='game_datetime',
            field=models.DateField(),
        ),
    ]
