# Generated by Django 5.1.2 on 2024-11-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/ppy default-profile.png', null=True, upload_to='profile_images'),
        ),
    ]
