# Generated by Django 5.1.2 on 2024-11-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default-profile.png', null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tel',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='team',
            name='administrators',
            field=models.ManyToManyField(related_name='administered_team', to='user.player'),
        ),
    ]
