# Generated by Django 5.1.2 on 2024-11-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='profile_images/default_team.jpg', null=True, upload_to=''),
        ),
    ]
