# Generated by Django 5.1.2 on 2024-11-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_team_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='profile_images/default_team.jpg', null=True, upload_to='profile_images'),
        ),
    ]
