# Generated by Django 5.1.2 on 2024-11-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='draws',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='loses',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.SmallIntegerField(default=0),
        ),
    ]
